export function AboutView() {
  return (
    <div className="px-[5%] py-6 w-3xl mx-auto">
      <section>
        <h1 className="text-xl font-bold text-(--text-h) mb-1">About</h1>
        <p className="text-sm text-(--text) mb-2">
          trvl365 is a travel blogging platform built for my web application development course.
          <br></br>
          This is a demo of the website, showcasing its UI, and how it works, with modifiable features disabled.
          It's had a few minor changes done post assignment, but these were mainly implemented to replace the required backend this usually has.
        </p>
      </section>
      <section>
        <h2 className="text-xl font-bold text-(--text-h) mb-1">Blog Contents</h2>
        <p className="text-sm text-(--text) mb-2">
          All blogs (blogs details, and interactions) were generated by AI outside of the assignment, with images to be implemented.
        </p>
      </section>
      <section>
        <h2 className="text-xl font-bold text-(--text-h) mb-1">Attributions</h2>
        <p className="text-sm text-(--text) mb-2">
          to be implemented, once images are sourced.
        </p>
      </section>
    </div>
  );
}